const sharedShellScript = document.createElement("script");
sharedShellScript.src = "/js/shared-shell.js";
document.head.appendChild(sharedShellScript);

const sessionKey = "plano-pneumatic-session";
const page = document.querySelector("[data-admin-page]");
const pageType = page.dataset.adminPage;
const apiOrigin = window.location.hostname === "planopneumatic-production.up.railway.app" ? "https://planopneumaticapi-production.up.railway.app" : window.location.origin;
function apiUrl(url) { return new URL(url, apiOrigin).toString(); }
function session() { try { return JSON.parse(localStorage.getItem(sessionKey)); } catch { return null; } }
async function api(url, options = {}) { const current = session(); if (!current?.token) { location.href = "/"; return null; } let response; try { response = await fetch(apiUrl(url), { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${current.token}`, ...(options.headers || {}) } }); } catch { throw new Error("A API está indisponível no momento. Tente novamente em instantes."); } if (response.status === 401) { localStorage.removeItem(sessionKey); location.href = "/"; return null; } if (!response.ok) { const error = await response.json().catch(() => ({ message: "Não foi possível concluir esta operação." })); throw new Error(error.message); } return response.status === 204 ? null : response.json(); }
function profile(user) { document.querySelector("#profile-name").textContent = user.name; document.querySelector("#profile-role").textContent = user.role === "admin" ? "Administrador" : user.role === "manager" ? "Gerente" : user.role; document.querySelector("#profile-initials").textContent = user.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase(); }
function shellLinks() { document.querySelectorAll("[data-logout]").forEach((button) => button.addEventListener("click", async () => { try { await api("/api/auth/logout", { method: "POST" }); } catch {} localStorage.removeItem(sessionKey); location.href = "/"; })); }
function card(label, value, tone = "blue") { return `<article class="indicator-card ${tone}"><div class="indicator-top"><span>${label}</span><span class="indicator-mark">↗</span></div><strong>${value}</strong><small>Dados atuais</small></article>`; }
async function pending() { const data = await api("/api/pending"); document.querySelector("#page-content").innerHTML = `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Fila operacional</p><h2>Casos que precisam de atenção</h2></div><span class="process-status">${data.items.length} pendentes</span></div><div class="table-wrap"><table><thead><tr><th>Processo</th><th>Cliente</th><th>Tipo</th><th>Pendência</th><th>Risco</th><th>Responsável</th></tr></thead><tbody>${data.items.map((item) => `<tr><td><strong>${item.id}</strong></td><td>${item.client}</td><td>${item.type}</td><td>${item.description}</td><td><span class="table-status ${item.risk === "Alto" ? "red" : "orange"}">${item.risk}</span></td><td>${item.responsible}</td></tr>`).join("") || `<tr><td colspan="6">Nenhuma pendência no seu escopo.</td></tr>`}</tbody></table></div></section>`; }
async function reports() { const data = await api("/api/reports/summary"); document.querySelector("#page-content").innerHTML = `<section class="indicator-grid report-cards">${card("Total de casos", data.totals.total)}${card("Pendências", data.totals.pending, "orange")}${card("Garantias em análise", data.totals.guarantees_in_analysis, "red")}${card("Concluídos", data.totals.completed, "green")}</section><section class="content-grid report-grid"><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Distribuição</p><h2>Casos por tipo</h2></div></div><div class="report-bars">${data.byType.map((item) => `<div class="report-bar"><div><strong>${item.label}</strong><span>${item.value}</span></div><i style="width:${Math.max(10, item.value / Math.max(data.totals.total, 1) * 100)}%"></i></div>`).join("") || "<p class=\"muted\">Sem dados.</p>"}</div></article><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Rastreabilidade</p><h2>Eventos recentes</h2></div></div><div class="event-list">${data.events.map((event) => `<div class="event"><span>${event.type}</span><div><strong>${event.id} · ${event.description}</strong><small>${event.responsible} · ${new Date(event.createdAt).toLocaleString("pt-BR")}</small></div></div>`).join("") || "<p class=\"muted\">Sem eventos.</p>"}</div></article></section>`; }
function settings() { document.querySelector("#page-content").innerHTML = `<section class="settings-grid"><article class="panel"><p class="eyebrow">Operação</p><h2>Configurações do sistema</h2><label class="setting-row"><span><strong>Alertas de pendência</strong><small>Exibir casos críticos no dashboard</small></span><input type="checkbox" checked data-setting="alerts" /></label><label class="setting-row"><span><strong>Atualização automática</strong><small>Atualizar indicadores ao abrir a tela</small></span><input type="checkbox" checked data-setting="refresh" /></label><label class="setting-row"><span><strong>Exigir documentação</strong><small>Bloquear avanços sem documentos mínimos</small></span><input type="checkbox" checked data-setting="documents" /></label></article><article class="panel"><p class="eyebrow">Padrão operacional</p><h2>Status principais</h2><div class="status-reference"><span class="table-status blue">Em andamento</span><span class="table-status orange">Pendente</span><span class="table-status red">Crítico</span><span class="table-status green">Concluído</span></div><p class="muted">As permissões e transições de cada papel serão aplicadas nos módulos de processo.</p></article></section>`; document.querySelectorAll("[data-setting]").forEach((input) => input.addEventListener("change", () => localStorage.setItem(`setting-${input.dataset.setting}`, input.checked))); }
async function account(user) { document.querySelector("#page-content").innerHTML = `<section class="panel account-panel"><p class="eyebrow">Meu acesso</p><h2>Configurações da conta</h2><p class="muted">Atualize seus dados pessoais. O perfil de acesso é administrado pelo sistema.</p><form id="account-form" class="form account-form"><label>Nome<input name="name" value="${user.name}" required /></label><label>E-mail<input value="${user.email}" disabled /></label><label>Nova senha<input name="password" type="password" placeholder="Deixe em branco para manter a atual" /></label><button class="button button-primary" type="submit">Salvar alterações <span>→</span></button><p id="account-feedback" class="feedback"></p></form></section>`; document.querySelector("#account-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const feedback = document.querySelector("#account-feedback"); try { const data = await api("/api/account", { method: "PATCH", body: JSON.stringify({ name: form.name.value, password: form.password.value }) }); profile(data.user); feedback.textContent = "Dados atualizados."; feedback.className = "feedback success-feedback"; } catch (error) { feedback.textContent = error.message; } }); }
async function bootstrap() { const me = await api("/api/auth/me"); if (!me) return; profile(me.user); shellLinks(); const managersTab = document.querySelector('[data-tab="managers"]'); if (managersTab && me.user.role !== "admin") managersTab.remove(); try { if (pageType === "pending") await pending(); if (pageType === "reports") await reports(); if (pageType === "reports-team") await teamPerformance(); if (pageType === "reports-managers") await managerPerformance(); if (pageType === "users") await users(); if (pageType === "settings") settings(); if (pageType === "account") await account(me.user); } catch (error) { document.querySelector("#page-content").innerHTML = `<section class="panel"><p class="feedback">${error.message}</p></section>`; } }

async function users() {
	const data = await api("/api/users");
	const isAdmin = session()?.user?.role === "admin";
	const roleOptions = isAdmin ? '<option value="operator">Operador</option><option value="manager">Gerente</option>' : '<option value="operator">Operador</option>';
	const managers = data.users.filter((user) => user.role === "manager" && user.active);
	const managerOptions = (currentManagerId) => `<option value="">Sem time</option>${managers.map((manager) => `<option value="${manager.id}" ${manager.id === currentManagerId ? "selected" : ""}>${manager.name}</option>`).join("")}`;
	document.querySelector("#page-content").innerHTML = `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Acessos</p><h2>Usuarios e perfis</h2></div><span class="process-status">${data.users.length} usuarios</span></div><form id="create-user-form" class="create-user-form"><div class="editor-grid"><label>Nome<input name="name" required /></label><label>E-mail<input name="email" type="email" required /></label><label>Senha inicial<input name="password" type="password" minlength="8" required /></label><label>Perfil<select name="role">${roleOptions}</select></label>${isAdmin ? `<label>Time<select name="managerId">${managerOptions(null)}</select></label>` : ""}</div><div class="form-actions"><p id="create-user-feedback" class="feedback"></p><button class="button button-primary" type="submit">Criar conta <span>+</span></button></div></form><div class="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Time</th><th>Status</th><th>Ação</th></tr></thead><tbody>${data.users.map((user) => `<tr><td><strong>${user.name}</strong></td><td>${user.email}</td><td>${user.role === "manager" ? "Gerente" : user.role}</td><td>${isAdmin && user.role === "operator" ? `<select data-transfer-user-id="${user.id}">${managerOptions(user.managerId)}</select>` : (user.managerName || (user.role === "manager" ? "—" : "Sem time"))}</td><td><span class="table-status ${user.active ? "green" : "red"}">${user.active ? "Ativo" : "Bloqueado"}</span></td><td>${user.id === session()?.user?.id ? "Conta atual" : `<button class="button button-secondary user-status-button" type="button" data-user-id="${user.id}" data-active="${!user.active}">${user.active ? "Bloquear" : "Ativar"}</button>`}</td></tr>`).join("")}</tbody></table></div></section>`;
	document.querySelectorAll(".user-status-button").forEach((button) => button.addEventListener("click", async () => {
		button.disabled = true;
		try { await api(`/api/users/${button.dataset.userId}/status`, { method: "PATCH", body: JSON.stringify({ active: button.dataset.active === "true" }) }); await users(); }
		catch (error) { document.querySelector("#create-user-feedback").textContent = error.message; button.disabled = false; }
	}));
	document.querySelectorAll("[data-transfer-user-id]").forEach((select) => select.addEventListener("change", async () => {
		select.disabled = true;
		try { await api(`/api/users/${select.dataset.transferUserId}/team`, { method: "PATCH", body: JSON.stringify({ managerId: select.value || null }) }); await users(); }
		catch (error) { document.querySelector("#create-user-feedback").textContent = error.message; select.disabled = false; }
	}));
	document.querySelector("#create-user-form").addEventListener("submit", async (event) => {
		event.preventDefault();
		const form = event.currentTarget;
		const feedback = document.querySelector("#create-user-feedback");
		const button = form.querySelector("button[type=submit]");
		button.disabled = true;
		feedback.textContent = "";
		try {
			await api("/api/users", { method: "POST", body: JSON.stringify({ name: form.name.value, email: form.email.value, password: form.password.value, role: form.role.value, managerId: form.managerId ? form.managerId.value || undefined : undefined }) });
			await users();
		} catch (error) {
			feedback.textContent = error.message;
		} finally {
			button.disabled = false;
		}
	});
}

async function teamPerformance() {
	const data = await api("/api/reports/team-performance");
	const teamCards = data.teams.map((team) => `<article class="panel"><div class="panel-heading"><div><p class="eyebrow">Time</p><h2>${team.managerName}</h2></div><span class="process-status">${team.partsRegistered} peças</span></div><div class="table-wrap"><table><thead><tr><th>Integrante</th><th>Perfil</th><th>Processos cadastrados</th><th>Peças cadastradas</th></tr></thead><tbody>${team.members.map((member) => `<tr><td><strong>${member.name}</strong></td><td>${member.role === "manager" ? "Gerente" : "Operador"}</td><td>${member.casesRegistered}</td><td>${member.partsRegistered}</td></tr>`).join("")}</tbody></table></div></article>`).join("") || '<p class="muted">Nenhum time encontrado.</p>';
	document.querySelector("#page-content").innerHTML = `<section class="team-performance-grid">${teamCards}</section>`;
}

async function managerPerformance() {
	const data = await api("/api/reports/manager-performance");
	document.querySelector("#page-content").innerHTML = `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Avaliação</p><h2>Desempenho dos gerentes</h2></div><span class="process-status">${data.managers.length} gerentes</span></div><div class="table-wrap"><table><thead><tr><th>Gerente</th><th>Time</th><th>Ações</th><th>Navegações</th><th>Cliques</th><th>Dias ativos</th><th>Última atividade</th><th>Casos do time</th><th>Concluídos</th><th>Score</th></tr></thead><tbody>${data.managers.map((manager) => `<tr><td><strong>${manager.name}</strong></td><td>${manager.teamSize}</td><td>${manager.totalActions}</td><td>${manager.navigationCount}</td><td>${manager.clickCount}</td><td>${manager.activeDays}</td><td>${manager.lastActivityAt ? new Date(manager.lastActivityAt).toLocaleString("pt-BR") : "—"}</td><td>${manager.teamCases}</td><td>${manager.teamCompletedCases}</td><td><span class="table-status ${manager.engagementScore >= 60 ? "green" : manager.engagementScore >= 30 ? "orange" : "red"}">${manager.engagementScore}</span></td></tr>`).join("") || `<tr><td colspan="10">Nenhum gerente cadastrado.</td></tr>`}</tbody></table></div></section>`;
}

bootstrap();
